version: '3.8'

networks:
  dockernet:
    external: true

services:
  ipxe:
    build: ./docker
    container_name: ipxe-server
    networks:
      dockernet:
        ipv4_address: 172.26.222.254
    environment:
      - SERVER_IP=172.26.200.211
      - NFS_IP=172.26.200.174
      - SMB_IP=172.26.200.174
    volumes:
      - /mnt/smb/ipxe:/pxeboot
    ports:
      - "65100:65100"
      - "69:69/udp"
    restart: unless-stopped
